name: timely
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animated_reorderable_list: ^1.1.5
  day_night_time_picker: ^1.3.1
  duration_picker: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  uuid: ^4.5.1
  wheel_picker: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
